name: strongR-frida

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check latest Frida version
        id: check_version
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              const { data: { tag_name: ver } } = await github.rest.repos.getLatestRelease({
                owner: 'frida',
                repo: 'frida'
              });
              console.log(`Latest frida version: ${ver}`);
              core.setOutput('FRIDA_VERSION', ver);
            } catch (e) {
              core.setFailed(e.message);
            }

      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.check_version.outputs.FRIDA_VERSION }}
          release_name: ${{ steps.check_version.outputs.FRIDA_VERSION }}
          draft: false
          prerelease: false

      - name: Setup build environment
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3-dev python3-pip
          pip3 install lief graphlib

      - name: Build frida for Android
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

          echo "Cloning frida version: ${{ steps.check_version.outputs.FRIDA_VERSION }}"
          git clone https://github.com/frida/frida.git --branch ${{ steps.check_version.outputs.FRIDA_VERSION }} --single-branch

          export ANDROID_NDK_ROOT=$ANDROID_HOME/ndk-bundle

          git clone https://github.com/hluwa/Patchs.git

          cd frida
          for path in ../Patchs/strongR-frida/*; do
            if [ -d "$path" ]; then
              name=$(basename "$path")
              if [ -d "subprojects/$name" ]; then
                echo "Apply patches in $path to frida/subprojects/$name"
                cd subprojects/$name
                git am ../../../Patchs/strongR-frida/$name/*.patch
                cd ../..
              fi
            fi
          done
          cd ..

          ARCHES="android-arm android-arm64 android-x86 android-x86_64"
          for ARCH in $ARCHES; do
            mkdir build-$ARCH
            cd build-$ARCH
            ../frida/configure --host=$ARCH
            make
            cd ..
          done

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frida-server-builds
          path: |
            build-android-arm/frida-server
            build-android-arm64/frida-server
            build-android-x86/frida-server
            build-android-x86_64/frida-server
